name: api-ci
on:
  pull_request:
    paths: [ "api/**" ]
  push:
    paths: [ "api/**" ]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Install
        working-directory: api
        run: npm ci || npm i

